[package]
name = "misc"
version = "0.1.0"
authors = ["Vytautas Krivickas <vytautas1996@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typenum = '1.11.2'
types = { path = '../../types' }
