[package]
name = 'spec_test_utils'
version = '0.1.0'
edition = '2018'

[dependencies]
ssz_new = { path = '../utils/ssz_new' }
serde = { version = '1.0', features = ['derive']}
serde_repr = '0.1.5'
serde_yaml = '0.8.11'
